using technical.assessment.api.Services;

namespace technical.assessment.unit.tests.Services;

public class AmountConversionServiceTests
{
    private readonly AmountConversionService _sut = new();

    [Theory]
    [InlineData("0", "ZERO DOLLAR")]
    [InlineData("1", "ONE DOLLAR")]
    [InlineData("11", "ELEVEN DOLLARS")]
    [InlineData("123", "ONE HUNDRED AND TWENTY-THREE DOLLARS")]
    [InlineData("4321", "FOUR THOUSAND THREE HUNDRED AND TWENTY-ONE DOLLARS")]
    [InlineData("12345", "TWELVE THOUSAND THREE HUNDRED AND FORTY-FIVE DOLLARS")]
    [InlineData("123456", "ONE HUNDRED AND TWENTY-THREE THOUSAND FOUR HUNDRED AND FIFTY-SIX DOLLARS")]
    [InlineData("1234567", "ONE MILLION TWO HUNDRED AND THIRTY-FOUR THOUSAND FIVE HUNDRED AND SIXTY-SEVEN DOLLARS")]
    [InlineData("12345678", "TWELVE MILLION THREE HUNDRED AND FORTY-FIVE THOUSAND SIX HUNDRED AND SEVENTY-EIGHT DOLLARS")]
    [InlineData("123456789", "ONE HUNDRED AND TWENTY-THREE MILLION FOUR HUNDRED AND FIFTY-SIX THOUSAND SEVEN HUNDRED AND EIGHTY-NINE DOLLARS")]
    [InlineData("1234567890", "ONE BILLION TWO HUNDRED AND THIRTY-FOUR MILLION FIVE HUNDRED AND SIXTY-SEVEN THOUSAND EIGHT HUNDRED AND NINETY DOLLARS")]
    [InlineData("1.01", "ONE DOLLAR AND ONE CENT")]
    [InlineData("11.23", "ELEVEN DOLLARS AND TWENTY-THREE CENTS")]
    [InlineData("123.55", "ONE HUNDRED AND TWENTY-THREE DOLLARS AND FIFTY-FIVE CENTS")]
    [InlineData("4321.67", "FOUR THOUSAND THREE HUNDRED AND TWENTY-ONE DOLLARS AND SIXTY-SEVEN CENTS")]
    [InlineData("12345.86", "TWELVE THOUSAND THREE HUNDRED AND FORTY-FIVE DOLLARS AND EIGHTY-SIX CENTS")]
    [InlineData("123456.39", "ONE HUNDRED AND TWENTY-THREE THOUSAND FOUR HUNDRED AND FIFTY-SIX DOLLARS AND THIRTY-NINE CENTS")]
    [InlineData("1234567.42", "ONE MILLION TWO HUNDRED AND THIRTY-FOUR THOUSAND FIVE HUNDRED AND SIXTY-SEVEN DOLLARS AND FORTY-TWO CENTS")]
    [InlineData("12345678.20", "TWELVE MILLION THREE HUNDRED AND FORTY-FIVE THOUSAND SIX HUNDRED AND SEVENTY-EIGHT DOLLARS AND TWENTY CENTS")]
    [InlineData("123456789.5", "ONE HUNDRED AND TWENTY-THREE MILLION FOUR HUNDRED AND FIFTY-SIX THOUSAND SEVEN HUNDRED AND EIGHTY-NINE DOLLARS AND FIFTY CENTS")]
    [InlineData("1234567890.00", "ONE BILLION TWO HUNDRED AND THIRTY-FOUR MILLION FIVE HUNDRED AND SIXTY-SEVEN THOUSAND EIGHT HUNDRED AND NINETY DOLLARS")]
    public void ConvertAmountToWords(string amount, string expectedWords)
    {
        // Act
        var actualWords = _sut.ConvertAmountToWords(amount);
        
        // Assert
        Assert.Equal(expectedWords, actualWords);
    }
}